theme = "hyde-hyde"
baseURL = "https://andypalmer.dev/"
languageCode = "en-au"
title = "Andy Palmer"
disqusShortname = "andy-palmer"
#disableKinds = ["categories"]

[params]
  description = "Thoughts on all things programming"
  #themeColor = "theme-base-08"

  # sidebar, copyright & license
  copyright = "Andy Palmer"
  showBuiltWith = true

  # https://highlightjs.org
  highlightjs = true
  highlightjsstyle = "github"
  highlightjslanguages = ["csharp,cmd"]

  postNavigation = false
  
[params.social]
	github = "palmerandy"
  linkedin = "palmer-andy"
  stackoverflow = "3566997"
  gravatar = "andypalmer@outlook.com.au"
  
[[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "About Me"
  weight = 200
  identifier = "about"
  url = "/about/me"

[[menu.main]]
  name = "Professional Experience"
  weight = 300
  identifier = "experience"
  url = "/about/professional-experience"

[[menu.main]]
  weight = 400
  name = "Tags"
  identifier = "tags"
  url = "/tags/"


